# Adaptado de: https://github.com/thomaseizinger/github-action-gitflow-release-workflow/blob/dev/.github/workflows/draft-new-release.yml

name: Prepara lançamento de release

on:
  workflow_dispatch:
    inputs:
      release-type:
        type: choice
        description: 'Tipo de release'
        required: true
        options:
          - major
          - minor
        default: minor

env:
  RELEASE_TYPE: ${{ github.event.inputs.release-type }}
  REPO_OWNER: ${{ github.repository_owner }}
  REPO_NAME: ${{ github.repository }}
  RUN_ID: ${{ github.run_id }}

jobs:
  draft-release:
    if: github.repository_owner == 'GustavoHenriqueP'
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: './.nvmrc'

      - name: Bump version in package.json
        run: npm version $RELEASE_TYPE --no-git-tag-version --force

      - name: Set new envs
        run: |
          # New version
          NEW_VERSION=$(npm pkg get version | jq -r)
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

          # New branch
          echo "NEW_BRANCH=release/$NEW_VERSION" >> $GITHUB_ENV

      - name: Update changelog file
        run: node .github/scripts/update-changelog.js $NEW_VERSION $REPO_OWNER $REPO_NAME

      - name: Create release branch
        run: git checkout -b $NEW_BRANCH

      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "noreply@github.com"

      - name: Commit changelog and manifest files
        id: make-commit
        run: |
          git add CHANGELOG.md package.json
          git commit -m "chore: prepare release $NEW_VERSION"

          echo "commit=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Push new branch
        run: git push origin $NEW_BRANCH

      - name: Create pull request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_OUTPUT: ${{ steps.make-commit.outputs.commit }}
        run: |
          gh pr create --base main --head $NEW_BRANCH \
            --title "Publicação: v$NEW_VERSION" \
            --body "Olá! Esse PR foi criado automaticamente em resposta ao acionamento manual do seguinte workflow: https://github.com/$REPO_NAME/actions/runs/$RUN_ID.
            O changelog e a versão dos arquivos de manifesto foi atualizada nesse commit: $COMMIT_OUTPUT.

            Com a criação desse PR, um workflow de deploy também foi acionado e já publicou essa versão em staging no servidor.
            Por favor, revise as alterações antes do merge. Quando o mesmo for realizado, a versão será publicada em produção automaticamente."

      - name: Delete new created branch on failure (if PR is not created)
        if: failure()
        run: |
          if git ls-remote --exit-code --heads origin $NEW_BRANCH; then
            echo "Branch $NEW_BRANCH encontrada. Excluindo..."
            git push origin --delete $NEW_BRANCH
          else
            echo "Branch $NEW_BRANCH não existe. Nada para excluir."
          fi

  deploy-staging:
    needs: draft-release
    uses: ./.github/workflows/deploy-staging.yaml
# TODO: Talvez já colocar um script que irá rodar o workflow manual para preparar o release
