# Adaptado de: https://github.com/thomaseizinger/github-action-gitflow-release-workflow/blob/dev/.github/workflows/draft-new-release.yml

name: Prepara lançamento de hotfix

on:
  push:
    branches:
      - hotfix/**

env:
  BRANCH_NAME: ${{ github.event.ref }}
  REPO_OWNER: ${{ github.repository_owner }}
  REPO_NAME: ${{ github.repository }}
  RUN_ID: ${{ github.run_id }}

jobs:
  draft-hotfix:
    if: github.repository_owner == 'GustavoHenriqueP'
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: './.nvmrc'

      - name: Set new version env variable
        run: |
          # New version
          NEW_VERSION=${BRANCH_NAME#hotfix/}
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Bump version in package.json
        run: npm version $NEW_VERSION --no-git-tag-version --force

      - name: Update changelog file
        run: node .github/scripts/update-changelog.js $NEW_VERSION $REPO_OWNER $REPO_NAME

      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "noreply@github.com"

      - name: Commit changelog and manifest files
        id: make-commit
        run: |
          git add CHANGELOG.md package.json
          git commit -m "chore: prepara hotfix $NEW_VERSION"

          echo "commit=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Push changes
        run: git push origin $BRANCH_NAME

      - name: Create pull request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_OUTPUT: ${{ steps.make-commit.outputs.commit }}
        run: |
          gh pr create --base main --head $BRANCH_NAME \
            --title "Publicação (hotfix): v$NEW_VERSION" \
            --body "Olá!

            Esse PR foi criado automaticamente em resposta ao push de um novo hotfix. Segue workflow acionado: https://github.com/$REPO_NAME/actions/runs/$RUN_ID.
            O changelog e a versão dos arquivos de manifesto foram atualizados nesse commit: $COMMIT_OUTPUT.

            Uma validação de código com verificação de formatação, lint e testes estará sendo realizada.
            Por favor, revise as alterações e o resultado da validação antes do merge. Quando o mesmo for realizado, a versão será publicada em produção automaticamente."
