name: Valida PR para main

on:
  workflow_run:
    workflows: ['Prepara lançamento de release', 'Prepara lançamento de hotfix']
    types:
      - completed
  pull_request:
    branches:
      - main
    paths:
      - src/**
      - public/**
      - .env.*
      - '*.html'
      - '!src/testing/**'
      - '!**.{test,spec}.[jt]sx?'
      - '!**.stories.[jt]sx?'

env:
  BRANCH_REF: ${{ github.event.workflow_run.head_branch || github.event.workflow_run.ref_name || github.head_ref }}

jobs:
  check-head-branch:
    runs-on: ubuntu-22.04
    steps:
      - name: Check head branch
        run: |
          BRANCH_NAME="${{ env.BRANCH_REF }}"
          echo "${{ github.event.workflow_run.head_branch }}"
          echo "${{ github.event.workflow_run.ref_name }}"
          echo "${{ github.head_ref }}"

          if [[ ! "$BRANCH_NAME" =~ ^(release/|hotfix/) ]]; then
            echo "::error::Pull requests para 'main' só podem vir de branches 'release/**' ou 'hotfix/**'."
            exit 1  # Cancela o workflow com erro
          fi

  lint:
    needs: check-head-branch
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH_REF }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 'latest'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: './.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

  format-check:
    needs: check-head-branch
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH_REF }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 'latest'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: './.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Check code formatting
        run: pnpm format:check

  test:
    needs: check-head-branch
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH_REF }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 'latest'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: './.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Test
        run: pnpm test
