name: Valida PR para main

on:
  workflow_call:
    inputs:
      branch_ref:
        description: 'Branch para validar'
        required: false
        type: string

env:
  BRANCH_REF: ${{ inputs.branch_ref || github.ref }}

jobs:
  check-head-branch:
    runs-on: ubuntu-22.04
    steps:
      - name: Check head branch
        run: |
          BRANCH_NAME="${{ env.BRANCH_REF }}"

          if [[ ! "$BRANCH_NAME" =~ ^(release/|hotfix/) ]]; then
            echo "::error::Pull requests para 'main' só podem vir de branches 'release/**' ou 'hotfix/**'."
            exit 1  # Cancela o workflow com erro
          fi

  lint:
    needs: check-head-branch
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH_REF }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 'latest'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: './.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

  format-check:
    needs: check-head-branch
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH_REF }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 'latest'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: './.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Check code formatting
        run: pnpm format:check

  test:
    needs: check-head-branch
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH_REF }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 'latest'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: './.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Test
        run: pnpm test
